### PR TITLE
Actor health

### PR DESCRIPTION
**Pull request by smudge202**
/CC @herecydev  @mattridgway

### CODE REVIEW

**Comment by smudge202** [comment]
Probably as good a place as any to have this discussion.

Having slept on it, I don't like what we've done so far regarding ticking the engine.  We don't need to enforce that the engine even has a "tick".  We can remove the concept of _ticks_ completely, and just allow subscription by interval.

I also think we need to add a new issue regarding the engine notifications which should precede all other work such as #3 .

Once we have this observer pattern (or a superseded design) in place, then think again about the actors, health, etc?

**Comment by herecydev** [comment]
Sorry about last night. Super burned out.. Probably wasn't too wise to try coding. 

On topic, I'm not sure about ticks at the moment. I'm not leaning any specific way. However I do agree that this blocks anything we have. So you're right about making it an issue.

**Comment by smudge202** [comment]
Don't worry about last night. Hope you're feeling refreshed! In my experience, when you don't understand or _get_ something I'm trying to explain, although I might not realise at the time, it usually means I'm preaching something that doesn't make sense to anyone but me (and is wrong).

@mattridgway nd I spoke about this quite a bit today. Going to formulate some viewpoints and intent on the wiki, then come back to this PR once we agree on direction. Exciting things in the pipeline though!

**Comment by mattridgway** [comment]
@herecydev - are we getting rid of this?

**Comment by smudge202** [comment]
Yes, though was leaving it here to show it's fine to kill off branches if they're wrong (and in case there's any more code we want to nick).

**Pull request closed without merging**
